#!/usr/bin/env bash
#-*- coding: utf-8 -*-

curl \
    -X POST 'https://api.qqbot.jokerhub.cn/send_group_msg' \
    -H 'Content-Type: application/json' \
    -H "Authorization: Bearer $1" \
    -d '{
            "group_id": "753649704",
            "message": [
                {
                    "type": "text",
                    "data": {
                        "text": "test"
                    }
                }
            ]
        }'
