#!/usr/bin/env bash
#-*- coding: utf-8 -*-

# NapCatQQ: https://github.com/NapNeko/NapCatQQ
# NapCatQQ HomePage: https://napneko.github.io

script_file="napcat.sh"
if [ ! -f $script_file ]; then
    # 本地不存在安装脚本，下载它
    curl -o $script_file https://nclatest.znin.net/NapNeko/NapCat-Installer/main/script/install.sh
fi

if command -v xvfb-run >/dev/null 2>&1; then
    # 已安装命令，直接运行
    xvfb-run -a /root/Napcat/opt/QQ/qq --no-sandbox
else
    # 未安装命令，执行安装脚本
    sudo bash napcat.sh \
        --docker n \
        --cli y    \
        --proxy 0  \
        --force
fi

# 安装位置: 
# /root/Napcat 
# 启动 Napcat (无需 sudo): 
#   xvfb-run -a /root/Napcat/opt/QQ/qq --no-sandbox
#  
# 后台运行 Napcat (使用 screen, 无需 sudo): 
#   启动: screen -dmS napcat bash -c "xvfb-run -a /root/Napcat/opt/QQ/qq --no-sandbox"
#   带账号启动: screen -dmS napcat bash -c "xvfb-run -a /root/Napcat/opt/QQ/qq --no-sandbox  -q QQ号码"
#   附加到会话: screen -r napcat (按 Ctrl+A 然后按 D 分离)
#   停止会话: screen -S napcat -X quit
#  
# Napcat 相关信息:
#   插件位置: /root/Napcat/opt/QQ/resources/app/app_launcher/napcat
#   WebUI Token: 查看 /root/Napcat/opt/QQ/resources/app/app_launcher/napcat/config/webui.json 文件获取
#
# TUI-CLI 工具用法 (napcat):
#   启动: napcat
