#!/usr/bin/env bash
#-*- coding: utf-8 -*-

# 安装位置: /home/pi/Napcat
# 启动 Napcat (无需 sudo):
xvfb-run -a /home/pi/Napcat/opt/QQ/qq --no-sandbox
# 后台运行 Napcat (使用 screen, 无需 sudo):
# screen -dmS napcat bash -c "xvfb-run -a /home/pi/Napcat/opt/QQ/qq --no-sandbox "
# 带账号启动: 
# screen -dmS napcat bash -c "xvfb-run -a /home/pi/Napcat/opt/QQ/qq --no-sandbox  -q QQ号码"
# 附加到会话: 
# screen -r napcat (按 Ctrl+A 然后按 D 分离)
# 停止会话: 
# screen -S napcat -X quit
# Napcat 相关信息:
# 插件位置: /home/pi/Napcat/opt/QQ/resources/app/app_launcher/napcat
# WebUI Token: 查看 /home/pi/Napcat/opt/QQ/resources/app/app_launcher/napcat/config/webui.json 文件获取