#!/usr/bin/env bash
#-*- coding: utf-8 -*-

echo "installing skinsystem (mysql, nginx, php, git)"
apt-get update
apt-get install mysql-server nginx php-fpm php-curl php-mysql php-gd git -y
cd /var/www
git clone https://github.com/riflowth/SkinSystem
cd SkinSystem
git checkout `git tag | sort -V | grep -v "\-rc" | tail -1`
rm -rf .git
rm -rf .gitignore
rm -rf *.md
cd ..
chmod 775 -R /var/www/SkinSystem && chown -R www-data:www-data /var/www/SkinSystem
pw=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '')
echo "Creating MySQL user skinsystem:$pw"
echo "CREATE USER 'skinsystem'@'localhost' IDENTIFIED BY '$pw'; \
CREATE DATABASE skinsrestorer; \
GRANT ALL PRIVILEGES ON skinsrestorer . * TO 'skinsystem'@'localhost';" | mysql && echo "MySQL user skinsystem:$pw was created"
echo "Have a nice day, remember to save your credentials!"