name: deploy site

on:
  push:
    branches:
      - master
    paths:
      - 'site/**'
      - '.github/workflows/site_deploy.yml'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.128.0'
        extended: true

    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: true  # Fetch Hugo themes (true FOR recursive)
        
    - name: Build and publish website
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        cd site && ./deploy
